Try using exposed
```
2021-08-12 15:07:10.909 [main] INFO  ktor.application - Autoreload is disabled because the development mode is off.
2021-08-12 15:07:11.009 [main] INFO  ktor.application - Responding at http://0.0.0.0:8080
2021-08-12 15:07:11.010 [main] INFO  ktor.application - Application started in 0.113 seconds.
2021-08-12 15:07:11.011 [main] INFO  ktor.application - Application started: io.ktor.application.Application@68e5eea7
2021-08-12 15:07:17.601 [eventLoopGroupProxy-4-1] DEBUG Exposed - SELECT VALUE FROM INFORMATION_SCHEMA.SETTINGS WHERE NAME = 'MODE'
SQL: SELECT VALUE FROM INFORMATION_SCHEMA.SETTINGS WHERE NAME = 'MODE'
2021-08-12 15:07:17.613 [eventLoopGroupProxy-4-1] DEBUG Exposed - CREATE TABLE IF NOT EXISTS USERS (ID INT AUTO_INCREMENT PRIMARY KEY, USERNAME VARCHAR(100) NOT NULL, PASSWORD VARCHAR(50) NOT NULL)
SQL: CREATE TABLE IF NOT EXISTS USERS (ID INT AUTO_INCREMENT PRIMARY KEY, USERNAME VARCHAR(100) NOT NULL, PASSWORD VARCHAR(50) NOT NULL)
2021-08-12 15:07:17.616 [eventLoopGroupProxy-4-1] DEBUG Exposed - CREATE INDEX USERS_USERNAME ON USERS (USERNAME)
SQL: CREATE INDEX USERS_USERNAME ON USERS (USERNAME)
2021-08-12 15:07:17.618 [eventLoopGroupProxy-4-1] DEBUG Exposed - CREATE TABLE IF NOT EXISTS SESSIONS (ID INT AUTO_INCREMENT PRIMARY KEY, USERNAME VARCHAR(100) NOT NULL, TOKEN VARCHAR(50) NOT NULL)
SQL: CREATE TABLE IF NOT EXISTS SESSIONS (ID INT AUTO_INCREMENT PRIMARY KEY, USERNAME VARCHAR(100) NOT NULL, TOKEN VARCHAR(50) NOT NULL)
2021-08-12 15:07:17.619 [eventLoopGroupProxy-4-1] DEBUG Exposed - CREATE INDEX SESSIONS_USERNAME ON SESSIONS (USERNAME)
SQL: CREATE INDEX SESSIONS_USERNAME ON SESSIONS (USERNAME)
2021-08-12 15:07:17.620 [eventLoopGroupProxy-4-1] DEBUG Exposed - CREATE INDEX SESSIONS_TOKEN ON SESSIONS (TOKEN)
SQL: CREATE INDEX SESSIONS_TOKEN ON SESSIONS (TOKEN)
2021-08-12 15:07:17.645 [eventLoopGroupProxy-4-1] DEBUG Exposed - SELECT USERS.ID, USERS.USERNAME, USERS.PASSWORD FROM USERS WHERE USERS.USERNAME = 'jmfayard'
2021-08-12 15:07:17.647 [eventLoopGroupProxy-4-1] WARN  Exposed - Transaction attempt #0 failed: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.USERNAME, USERS.PASSWORD FROM USERS WHERE USERS.USERNAME = ? LIMIT 1 [42102-200]. Statement(s): SELECT USERS.ID, USERS.USERNAME, USERS.PASSWORD FROM USERS WHERE USERS.USERNAME = ?
org.jetbrains.exposed.exceptions.ExposedSQLException: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "USERS" not found; SQL statement:
SELECT USERS.ID, USERS.USERNAME, USERS.PASSWORD FROM USERS WHERE USERS.USERNAME = ? LIMIT 1 [42102-200]
```